import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/providers/user-context";
import { cn } from "@/utils/cn";
import { MetaMaskProvider } from "@/providers/metamask-context";
import { NavbarDemo } from "@/components/navigation-menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-slate-950")}>
        <MetaMaskProvider>
          <UserProvider>
            <NavbarDemo />
            <div >{children}</div>
          </UserProvider>
        </MetaMaskProvider>
      </body>
    </html>
  );
}
