import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/providers/user-context";
import { cn } from "@/utils/cn";
import { MetaMaskProvider } from "@/providers/metamask-context";
import { NavbarDemo } from "@/components/navigation-menu";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const footerProps = {
  logoUrl: 'https://www.floatui.com/logo.svg',
  description: "NFT MarketPlace.",
  navItems: [
      { href: '/profile', name: 'My Profile' },
      { href: '/auction', name: 'Auctions' },
      { href: '/leaderboard', name: 'Leaderboard' },
      // Add more nav items as needed
  ],
  copyright: '© 2022 Float UI All rights reserved.',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(inter.className, "bg-black")}>
        <MetaMaskProvider>
          <UserProvider>
            <NavbarDemo />
            <div>{children}</div>
            <Footer {...footerProps} />
          </UserProvider>
        </MetaMaskProvider>
      </body>
    </html>
  );
}
